ui_print "**************************************************"
ui_print " - Update Sqlite3 library for SDMaid"
ui_print " - Only for x86_64 devices"
ui_print " - SDMaid SE don't supported"
ui_print " - Done"
ui_print "**************************************************"
